// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAU4ixm8up4Ra_sssQPbmjmF4mfx1lgYw',
    appId: '1:483919816962:web:3c96dcf8bf6adeb5d0ba1b',
    messagingSenderId: '483919816962',
    projectId: 'honbab-signal',
    authDomain: 'honbab-signal.firebaseapp.com',
    storageBucket: 'honbab-signal.appspot.com',
    measurementId: 'G-G1GCLJGPE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsJ8JtdgB_o1wH03rr1bPDkMFySxz_aoA',
    appId: '1:483919816962:android:02d46b8419348f7ed0ba1b',
    messagingSenderId: '483919816962',
    projectId: 'honbab-signal',
    storageBucket: 'honbab-signal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-X1QxVohby75LJEYWHi4aaK4_Xyx22Q',
    appId: '1:483919816962:ios:bab5b492c723f14fd0ba1b',
    messagingSenderId: '483919816962',
    projectId: 'honbab-signal',
    storageBucket: 'honbab-signal.appspot.com',
    iosBundleId: 'com.example.honbapSignalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl-X1QxVohby75LJEYWHi4aaK4_Xyx22Q',
    appId: '1:483919816962:ios:bab5b492c723f14fd0ba1b',
    messagingSenderId: '483919816962',
    projectId: 'honbab-signal',
    storageBucket: 'honbab-signal.appspot.com',
    iosBundleId: 'com.example.honbapSignalFlutter',
  );
}
